#!/bin/sh

set -eu

OUT_DIR=/tmp/tidb_binlog_test
STATUS_LOG="${OUT_DIR}/status.log"
max_commit_ts_old=0
max_commit_ts_new=0

for i in {1..15}
do
    binlogctl -pd-urls 127.0.0.1:2379 -cmd $1 > $STATUS_LOG 2>&1
    cat $STATUS_LOG

    count=`grep -c "$2" $STATUS_LOG` || true

    if [ $i -eq 1 ]; then
        max_commit_ts_old=`cat $STATUS_LOG | sed 's/.*MaxCommitTS:\([0-9]*\) .*/\1/g'`
    else
        max_commit_ts_new=`cat $STATUS_LOG | sed 's/.*MaxCommitTS:\([0-9]*\) .*/\1/g'`
    fi

    # if status is online, will check the max commit ts
    if [ $count -ne 1 ] || ([ $2 == "online" ] && [ $max_commit_ts_new -le $max_commit_ts_old ]); then
        if [ $i -eq 15 ]; then
            echo "status is not $2, or max commit ts is not update, old max commit ts is $max_commit_ts_old, new max commit ts is $max_commit_ts_new"
            exit 2
        else
            sleep 1
        fi
    else
        break
    fi
done