#!/bin/sh

set -ue

PORT=${1-8250}

OUT_DIR=/tmp/tidb_binlog_test

# kill pump, util no pump process is running
while :
do
        pump_num=`ps aux > temp && grep "pump -log-file ${OUT_DIR}/pump_${PORT}.log" temp | wc -l && rm temp`
        if [ $pump_num -ne 0 ]; then
                binlogctl -pd-urls 127.0.0.1:2379 -cmd pause-pump -node-id pump:$PORT || true
                sleep 1
        else
                break
        fi
done

echo "[$(date)] <<<<<< RUNNING pump  >>>>>>" >> "$OUT_DIR/pump_$PORT.log"

pump -log-file $OUT_DIR/pump_$PORT.log --addr=0.0.0.0:$PORT \
        --advertise-addr=127.0.0.1:$PORT \
        --pd-urls=http://127.0.0.1:2379 \
        --data-dir=$OUT_DIR/pump_$PORT \
        --node-id=pump:$PORT >> $OUT_DIR/pump_$PORT.log 2>&1
