#!/bin/sh

set -ue

OUT_DIR=/tmp/tidb_binlog_test

# kill drainer, util no drainer process is running
while :
do
        drainer_num=`ps aux > temp && grep "drainer -log-file" temp | wc -l && rm temp`
        if [ $drainer_num -ne 0 ]; then
                killall drainer || true
                sleep 1
        else
                break
        fi
done

config=${TEST_DIR-.}/drainer.toml

echo "[$(date)] <<<<<< START IN TEST ${TEST_NAME-} FOR: $config >>>>>>" >> "$OUT_DIR/drainer.log"

if [ -f "$config" ]
then
	drainer -log-file $OUT_DIR/drainer.log -config $config $* >> $OUT_DIR/drainer.log 2>&1
else
	cat - > "$OUT_DIR/drainer-config.toml" <<EOF
[security]
ssl-ca = "/Users/huangjiahao/go/src/github.com/pingcap/tidb-binlog/certs/ca.pem"
ssl-cert = "/Users/huangjiahao/go/src/github.com/pingcap/tidb-binlog/certs/server-cert.pem"
ssl-key = "/Users/huangjiahao/go/src/github.com/pingcap/tidb-binlog/certs/server-key.pem"
EOF
	drainer -log-file $OUT_DIR/drainer.log -config "$OUT_DIR/drainer-config.toml" -addr 0.0.0.0:8249 -advertise-addr MySQL_Server_5.7.21_Auto_Generated_Server_Certificate:8249 $* >> $OUT_DIR/drainer.log 2>&1
fi
