# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-name: "github.com/pingcap/tidb"
      - dependency-name: "github.com/pingcap/tidb/parser"
      - dependency-name: "github.com/pingcap/tidb-tools"
      - dependency-name: "github.com/pingcap/tipb"
      - dependency-name: "github.com/pingcap/kvproto"
